name: go-test
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      consul:
        image: consul:1.12.2
        env:
          CONSUL_BIND_INTERFACE: eth0
        ports:
          - 8500:8500/tcp

    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - uses: actions/checkout@v2

    - name: Run build
      run: go build .

    - name: Run vet
      run: |
        go vet .

    - name: Run testing
      run: go test ./... -v
