name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.0'

      - name: Run build - Linux
        run: go build -o go-git-sync-linux-amd64 .

      - name: Run build - Windows
        run: go build -o go-git-sync-windows-amd64.exe .
        env:
          GOOS: windows

      - name: Run build - Mac
        run: go build -o go-git-sync-darwin-amd64 .
        env:
          GOOS: darwin

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset Linux AMD64
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-git-sync-linux-amd64
          asset_name: go-git-sync-linux-amd64
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Windows AMD64
        id: upload-release-asset-windows
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-git-sync-windows-amd64.exe
          asset_name: go-git-sync-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset Darwin AMD64
        id: upload-release-asset-mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./go-git-sync-darwin-amd64
          asset_name: go-git-sync-darwin-amd64
          asset_content_type: application/octet-stream
